name: Run checks

on:
  push:

jobs:
  django-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: autograder_django_backend/requirements
        
      - name: Install dependencies
        run: |
          pip install -r autograder_django_backend/requirements/local.txt

      - name: Test through Pytest
        run: |
          cd autograder_django_backend
          pytest
